
production:
  adapter: mysql
  database: rere
  host: localhost
  port: 3306
  username: rere
  password: rere

development:
  adapter: mysql
  database: rere

development2:
  adapter: postgresql
  database: rere_d

test:
  adapter: postgresql
  database: rere_t
  
cucumber:
  adapter: postgresql
  database: rere_c
