# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: rere_d

test:
  adapter: postgresql
  database: rere_t
  
cucumber:
  adapter: postgresql
  database: rere_c
