
production:
  adapter: postgresql
  database: rere_p
  host: 127.0.0.1
  username: rere
  password: rere

development:
  adapter: postgresql
  database: rere_d

test:
  adapter: postgresql
  database: rere_t
  
cucumber:
  adapter: postgresql
  database: rere_c
